all:
	g++ -o main main.cpp principal.cpp universidade.cpp professor.cpp pessoa.cpp listaUniversidade.cpp listaDisciplinas.cpp listaDepartamento.cpp listaAlunos.cpp elUniversidade.cpp elDisciplina.cpp elDepartamento.cpp elAluno.cpp disciplina.cpp departamento.cpp aluno.cpp

clear:
	-rm main.cpp principal.cpp universidade.cpp professor.cpp pessoa.cpp listaUniversidade.cpp listaDisciplinas.cpp listaDepartamento.cpp listaAlunos.cpp elUniversidade.cpp elDisciplina.cpp elDepartamento.cpp elAluno.cpp disciplina.cpp departamento.cpp aluno.cpp